### PR TITLE
Add opacity property

### PR DESCRIPTION
**Pull request by vasturiano**
Fix for https://github.com/fernandojsg/aframe-line-component/issues/2

I went and added the feature. Let me know if you have interest in merging it upstream.

### CODE REVIEW

**Comment by fernandojsg** [comment]
@vasturiano thank you! :)

**Comment by vasturiano** [comment]
Great! :) Would you mind publishing a new version of the module to NPM?

**Comment by fernandojsg** [comment]
@vasturiano deployed! :)

**Comment by vasturiano** [comment]
Great, thanks @fernandojsg! If you're curious, I'm using the component on this project: https://github.com/vasturiano/3d-force-graph-vr

**Comment by fernandojsg** [comment]
@vasturiano that looks really nice! congrats :) I created some time ago a much simpler example of dots connected by lines and I used the distance to modulate the opacity https://threejs.org/examples/?q=draw#webgl_buffergeometry_drawcalls

**Comment by vasturiano** [comment]
@fernandojsg that example is so incredibly mesmerizing. :) I couldn't stop looking at it!

**Pull request merged**
